name: ht
description: Common types of HTTP operations
version: 0.0.0
repository: https://github.com/medz/ht

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  async: ^2.12.0
  mime: 2.0.0
  http_parser: ^4.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: 6.1.0
  test: ^1.24.0
