name: ht
description: Common types of HTTP operations
version: 0.0.0
repository: https://github.com/medz/ht

environment:
  sdk: ^3.10.0

dependencies:
  async: ^2.13.0
  mime: ^2.0.0
  http_parser: ^4.1.2

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
